name: Record VOO/QQQ close (KST 05:00)

on:
  schedule:
    - cron: '0 20 * * *'  # 매일 20:00 UTC = KST 05:00
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run fetch script
        run: node scripts/fetch.js
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "data: update closes [skip ci]"
            git push
          else
            echo "No changes"
          fi
